src/PTPSite.Web/ViewModels/Home/DiscussionViewModel.cs
using System.ComponentModel.DataAnnotations;
using PTPSite.Web.ViewModels.Comment;

namespace PTPSite.Web.ViewModels.Home
{
	public class DiscussionViewModel
	{
		[Required]
		[Display(Name = "Text")]
		[StringLength(256, MinimumLength = 10)]
		public string Text { get; set; }

		[Required]
		[Display(Name = "Text")]
		[StringLength(256, MinimumLength = 10)]
		public string TextEdit { get; set; }

		public string UserId { get; set; }

		public CommentViewModel[] Comments { get; set; }
	}
}

src/PTPSite.Web/Controllers/CommentController.cs
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PTPSite.Services;
using PTPSite.Web.Infrastructure;

namespace PTPSite.Web.Controllers
{
	[Authorize]
	[Route("comment")]
	public class CommentController : BaseController
	{
		private readonly ICommentService _commentService;
		private readonly UserManager<ApplicationUser> _userManager;

		public CommentController(ICommentService commentService, UserManager<ApplicationUser> userManager)
		{
			_commentService = commentService ?? throw new ArgumentNullException(nameof(commentService));
			_userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
		}

		[HttpPost]
		[Route("create")]
		public async Task<IActionResult> Create([FromForm(Name = "text")] string text, CancellationToken cancellationToken = default)
		{
			if (string.IsNullOrEmpty(text) || text.Length < 10 || text.Length > 256)
			{
				return BadRequest();
			}

			ApplicationUser user = await _userManager.GetUserAsync(User);

			if (user == null)
			{
				throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
			}

			var comment = new Comment
			{
				Text = text,
				Date = DateTime.Now,
				ByUserId = user.Id,
			};

			await _commentService.Create(comment, cancellationToken);

			return Refresh();
		}

		[HttpPost]
		[Route("edit")]
		public async Task<IActionResult> Edit([FromForm(Name = "id")] string id, [FromForm(Name = "text")] string text, CancellationToken cancellationToken = default)
		{
			if (id == null)
			{
				return BadRequest();
			}

			if (string.IsNullOrEmpty(text) || text.Length < 10 || text.Length > 256)
			{
				return BadRequest();
			}

			ApplicationUser user = await _userManager.GetUserAsync(User);

			if (user == null)
			{
				throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
			}

			Comment comment = await _commentService.Get(id, cancellationToken);

			if (comment.ByUserId != user.Id)
			{
				return BadRequest();
			}

			comment.Text = text;
			comment.Date = DateTime.Now;

			await _commentService.Edit(comment, cancellationToken);

			return Refresh();
		}

		[HttpPost]
		[Route("remove")]
		public async Task<IActionResult> Remove([FromForm(Name = "id")] string id, CancellationToken cancellationToken = default)
		{
			if (id == null)
			{
				return BadRequest();
			}

			ApplicationUser user = await _userManager.GetUserAsync(User);

			if (user == null)
			{
				throw new ApplicationException($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
			}

			Comment comment = await _commentService.Get(id, cancellationToken);

			if (user.Role != ApplicationRole.Administrator && comment.ByUserId != user.Id)
			{
				return BadRequest();
			}

			await _commentService.Remove(id, cancellationToken);

			return Refresh();
		}
	}
}

src/PTPSite.Web/Controllers/HomeController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PTPSite.Services;
using PTPSite.Web.Infrastructure;
using PTPSite.Web.ViewModels;
using PTPSite.Web.ViewModels.Comment;
using PTPSite.Web.ViewModels.Home;

namespace PTPSite.Web.Controllers
{
	[Route("")]
	public class HomeController : BaseController
	{
		private readonly ICommentService _commentService;
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public HomeController(ICommentService commentService, UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
		{
			_commentService = commentService ?? throw new ArgumentNullException(nameof(commentService));
			_userManager = userManager ?? throw new ArgumentNullException(nameof(userManager));
			_signInManager = signInManager ?? throw new ArgumentNullException(nameof(signInManager));
		}

		[Route("")]
		public IActionResult Index()
		{
			return View();
		}

		[Route("experience")]
		public IActionResult Experience()
		{
			return View();
		}

		[Route("education")]
		public IActionResult Education()
		{
			return View();
		}

		[Route("skills")]
		public IActionResult Skills()
		{
			return View();
		}

		[Route("interests")]
		public IActionResult Interests()
		{
			return View();
		}

		[Route("certifications")]
		public IActionResult Certifications()
		{
			return View();
		}

		[Route("error")]
		public IActionResult Error()
		{
			var viewModel = new ErrorViewModel
			{
				RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
			};

			return View(viewModel);
		}

		[Route("discussion")]
		public async Task<IActionResult> Discussion(CancellationToken cancellationToken = default)
		{
			bool isLoggedIn = _signInManager.IsSignedIn(User);

			ApplicationUser user = await _userManager.GetUserAsync(User);

			Comment[] comments = await _commentService.List(cancellationToken);

			CommentViewModel[] commentViewModels = comments
				.Select(x => new CommentViewModel(x)
				{
					CanEdit = isLoggedIn && x.ByUserId == user.Id,
					CanRemove = isLoggedIn && (x.ByUserId == user.Id || user.Role == ApplicationRole.Administrator),
				})
				.ToArray();

			var model = new DiscussionViewModel
			{
				Comments = commentViewModels,
				UserId = user?.Id,
			};

			return View(model);
		}
	}
}

src/PTPSite.Web/Views/Home/Certifications.cshtml
@{
	ViewData["Title"] = "CERTIFICATIONS";
}

<h2>@ViewData["Title"]</h2>
<br />
<div>
	<ul>
		<li>
			<p>Software University: C#, Java, JS, CSS, HTML, SQL</p>
			<ul>
				<li>
					<a href="https://softuni.bg/certificates/details/2127/fc5e4423">OOP (C#, Java, PHP)</a>
				</li>
			</ul>
			<br />
		</li>
		<li>
			<p>New Horizons Computer Learning Centers: HTML, CSS3, JavaScript & Responsive Design</p>
		</li>
		<li>
			<p>David Holding AD: Курс по програмиране за напреднали</p>
		</li>
		<li>
			<p>David Holding AD: Курс по информационни технологии</p>
		</li>
		<li>
			<p>David Holding AD: Курс по програмиране на C#</p>
		</li>
	</ul>
</div>
<br />

src/PTPSite.Web/Views/Home/Discussion.cshtml
@using PTPSite.Services
@model DiscussionViewModel
@inject SignInManager<ApplicationUser> Manager
@{
	ViewData["Title"] = "DISCUSSION";
}

<h2>@ViewData["Title"]</h2>
<br />
@{
	if (Manager.IsSignedIn(User))
	{
		<form id="createForm" asp-area="" asp-controller="Comment" asp-action="Create" method="post">
			<hr />
			<div asp-validation-summary="All" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="Text" style="font-size:20px;">Text</label>
				<textarea asp-for="Text" class="form-control" rows="4"></textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Add comment</button>
			</div>
		</form>
		<form id="editForm" asp-area="" asp-controller="Comment" asp-action="Edit" method="post" style="display: none;">
			<input id="editId" name="id" style="display: none;" />
			<hr />
			<div asp-validation-summary="All" class="text-danger"></div>
			<div class="form-group">
				<label asp-for="TextEdit" style="font-size:20px;">Text</label>
				<textarea asp-for="TextEdit" name="text" class="form-control" rows="4"></textarea>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Edit comment</button>
				<button id="editCancel" type="button" class="btn btn-primary">Cancel</button>
			</div>
		</form>
	}
	else
	{
		<div class="alert alert-info" role="alert">
			Please <a style="font-weight: bold; color: #2b3e50; text-decoration:underline;" asp-area="" asp-controller="Account" asp-action="Login">login</a> if you want to add/remove/edit comments.
		</div>
	}
}
<div class="comments">
	@{
		foreach (CommentViewModel viewModel in Model.Comments)
		{
			<hr />
			<div class="row row-comment">
				<div class="col-md-2">
					<span>@viewModel.ByUserName</span>
					<br />
					<span>@viewModel.Date</span>
				</div>
				<div class="col-md-6">
					@viewModel.Text
				</div>
				<div class="col-md-2 col-md-offset-2" style="text-align: right;">
					@if (viewModel.CanEdit)
					{
						<a id="editLink" href="javascript: void(0)" data-id="@viewModel.Id" data-text="@viewModel.Text">Edit</a>
					}
					@if (viewModel.CanRemove)
					{
						<form asp-area="" asp-controller="Comment" asp-action="Remove" method="post" style="display: inline-block;">
							<input name="id" value="@viewModel.Id" style="display:none;" />
							<button type="submit" class="btn-link">Remove</button>
						</form>
					}
				</div>
			</div>
		}
	}
</div>
<script>
	$(function () {
		var editForm = $("#editForm");
		var createForm = $("#createForm");
		var editCancel = $("#editCancel");

		$("#editLink").on("click", function () {
			createForm.hide();
			editForm.show();

			var id = $(this).data("id");
			var text = $(this).data("text");

			editForm.find("#editId").val(id);
			editForm.find("#TextEdit").val(text);
		});

		editCancel.on("click", function () {
			editForm.hide();
			createForm.show();
		});
	});
</script>

src/PTPSite.Web/Views/Home/Education.cshtml
@{
	ViewData["Title"] = "EDUCATION";
}

<h2>@ViewData["Title"]</h2>
<br />
<div class="row">
	<div class="col-md-6">
		<div>New Bulgarian University</div>
		<p>Computer science</p>
		<span class="text-primary">2015 - </span>
		<span class="text-primary" style="font-weight: bold;">Now</span>
	</div>
</div>
<br />
<div class="row">
	<div class="col-md-6">
		<div>Software University</div>
		<p>C#, Java, JS, CSS, HTML, SQL courses</p>
		<span class="text-primary">2014 - 2016</span>
	</div>
</div>
<br />
<div class="row">
	<div class="col-md-6">
		<div>ПМГ "Н. Обрешков" - Казанлък</div>
		<p>Computer science</p>
		<span class="text-primary">2009 - 2014</span>
	</div>
</div>
<br />

src/PTPSite.Web/Views/Home/Experience.cshtml
@{
	ViewData["Title"] = "EXPERIENCE";
}

<h2>@ViewData["Title"]</h2>
<br />
<div class="row">
	<div class="col-md-6">
		<div>Developer</div>
		<div>David Holding AD</div>
		<p>Specializing in Microsoft .NET software development.</p>
		<span class="text-primary">January 2014 - </span>
		<span class="text-primary" style="font-weight: bold;">Now</span>
	</div>
</div>
<br />

src/PTPSite.Web/Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Petar Petrov";
}
<h1 style="text-transform: uppercase;">
	Petar&nbsp;<span style="color: #bf5a16; font-weight: bold;">Petrov</span>
</h1>
<div>
	Developer · (359) 889-333-333 ·
	<a href="mailto:petarpetrovt@gmail.com" class="text-primary" style="font-size: 15px;">petarpetrovt@gmail.com</a>
</div>
<br />
<div class="row">
	<div class="col-md-3">
		<img class="img-responsive" style="max-width:200px;" src="~/images/placeholder.jpg" alt="my image" />
	</div>
	<div class="col-md-9">
		<p>
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi iaculis consequat libero et ultricies.
			Morbi interdum auctor nisl. Integer rutrum lacinia ante vitae tincidunt.
			Proin varius libero vitae erat finibus elementum.
			Cras in vehicula felis, ac vehicula elit.
			Cras sed sapien iaculis erat volutpat dignissim.
			In magna metus, pharetra ut mattis id, gravida sed augue.
			Maecenas mattis est tellus, eu fermentum tellus pharetra eget. Morbi fermentum consequat elit quis rutrum.
			Mauris a magna luctus, euismod nibh nec, semper tellus. Sed at purus nec nulla pulvinar rutrum vel a tellus.
			Nullam eget felis mauris. Proin elementum erat vel laoreet accumsan.
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md-offset-3 col-md-9">
		<a href="https://github.com/petarpetrovt" target="_blank" rel="nofollow" style="font-size: 40px;">
			<i class="devicons devicons-github_badge"></i>
		</a>
		<a href="https://stackoverflow.com/users/3323071/ptp" target="_blank" rel="nofollow" style="font-size: 40px;">
			<i class="devicons devicons-stackoverflow"></i>
		</a>
	</div>
</div>
<br />
<div class="row">
	<div class="col-md-12">

	</div>
</div>
<br />

src/PTPSite.Web/Views/Home/Interests.cshtml
@{
	ViewData["Title"] = "INTERESTS";
}

<h2>@ViewData["Title"]</h2>
<br />
<p>
	Apart from being a developer, I enjoy most of my time being outdoors.
	In the winter, I am an novice snowboarder. <br />
	During the warmer months here in Bulgaria, I enjoy mountain biking.
</p>
<p>
	When forced indoors, I follow a number of sci-fi and fantasy genre movies and television shows. <br />
	I spend a large amount of my free time exploring the latest technology advancements.
</p>
<br />

src/PTPSite.Web/Views/Home/Skills.cshtml
@{
	ViewData["Title"] = "SKILLS";
}

<h2>@ViewData["Title"]</h2>
<h6>PROGRAMMING LANGUAGES &amp; TOOLS</h6>
<br />
<div>
	<ul class="list-inline list-icons">
		<li>
			<i class="devicons devicons-dotnet"></i>
		</li>
		<li>
			<i class="devicons devicons-visualstudio"></i>
		</li>
		<li>
			<i class="devicons devicons-html5"></i>
		</li>
		<li>
			<i class="devicons devicons-css3"></i>
		</li>
		<li>
			<i class="devicons devicons-javascript"></i>
		</li>
		<li>
			<i class="devicons devicons-jquery"></i>
		</li>
		<li>
			<i class="devicons devicons-msql_server"></i>
		</li>
		<li>
			<i class="devicons devicons-bootstrap"></i>
		</li>
		<li>
			<i class="devicons devicons-less"></i>
		</li>
	</ul>
	<br />
	<div class="subheading">Workflow</div>
	<br />
	<ul>
		<li>
			<p>Front-end HTML5, CSS 3, JS, TS</p>
		</li>
		<li>
			<p>Back-end C#, ASP.NET CORE, SQL, PHP</p>
		</li>
		<li>
			<p>Agile Development &amp; Scrum</p>
		</li>
	</ul>
</div>
<br />